(()=>{"use strict";
const track=document.querySelector("#cardTrack"),streakEl=document.querySelector("#streak"),bestEl=document.querySelector("#best"),messageEl=document.querySelector("#message"),lowButton=document.querySelector("#lowButton"),highButton=document.querySelector("#highButton"),restartButton=document.querySelector("#restartButton");
const suits=["♠","♥","♦","♣"],rankNames={1:"A",11:"J",12:"Q",13:"K"},BEST_KEY="namharu-highlow-best-v1";
let currentCard=null,streak=0,best=Number(localStorage.getItem(BEST_KEY)||0),locked=false,round=0,deckItem=null;
function nextCandidate(){const pool=[];for(let rank=1;rank<=13;rank++){if(rank===currentCard.rank)continue;for(const suit of suits)pool.push({rank,suit,joker:false})}pool.push({joker:true},{joker:true});return pool[Math.floor(Math.random()*pool.length)]}
function rankLabel(rank){return rankNames[rank]||String(rank)}
function cardElement(card){const el=document.createElement("div");el.className="card";if(card.joker){el.classList.add("joker");el.innerHTML='<div class="corner">★</div><div class="suit">JOKER</div><div class="corner bottom">★</div>';return el}if(card.suit==="♥"||card.suit==="♦")el.classList.add("red");const rank=rankLabel(card.rank);el.innerHTML=`<div class="corner"><b>${rank}</b><span>${card.suit}</span></div><div class="suit">${card.suit}</div><div class="corner bottom"><b>${rank}</b><span>${card.suit}</span></div>`;return el}
function makeItem(card,label){const item=document.createElement("div");item.className="card-item";item.dataset.label=label;const caption=document.createElement("span");caption.textContent=label;item.append(caption,cardElement(card));return item}
function makeDeck(){const item=document.createElement("div");item.className="card-item deck-item";item.innerHTML='<span>다음 카드</span><div class="card back"></div>';return item}
function markCurrent(){track.querySelectorAll(".card-item:not(.deck-item)").forEach(item=>{item.classList.remove("current");item.querySelector("span").textContent=item.dataset.label});const items=[...track.querySelectorAll(".card-item:not(.deck-item)")];items.at(-1)?.classList.add("current");items.at(-1)?.querySelector("span")?.replaceChildren("현재 카드")}
function appendCard(card,result){const item=makeItem(card,`${round}번째 카드`);const mark=document.createElement("b");mark.className=`result-mark${result.win?"":" lose"}`;mark.textContent=result.win?"성공":"실패";item.querySelector(".card").append(mark);track.insertBefore(item,deckItem);markCurrent();requestAnimationFrame(()=>track.parentElement.scrollTo({left:track.parentElement.scrollWidth,behavior:"smooth"}))}
function setButtons(enabled){lowButton.disabled=!enabled;highButton.disabled=!enabled}
function isWin(choice,next){if(currentCard.joker||next.joker)return{win:true,reason:"조커! 무조건 승리"};if(currentCard.rank===1||next.rank===1)return{win:true,reason:"A는 1 또는 14! 승리"};const win=choice==="high"?next.rank>currentCard.rank:next.rank<currentCard.rank;return{win,reason:win?"정답! 연승이 이어집니다.":"아쉽지만 틀렸어요."}}
function choose(choice){if(locked)return;locked=true;setButtons(false);const next=nextCandidate(),result=isWin(choice,next);round+=1;appendCard(next,result);messageEl.textContent=result.reason;messageEl.className=`message ${result.win?"win":"lose"}`;
  if(result.win){streak++;best=Math.max(best,streak);localStorage.setItem(BEST_KEY,best);streakEl.textContent=streak;bestEl.textContent=best;setTimeout(()=>{currentCard=next;messageEl.textContent=next.joker?"조커가 현재 카드입니다. 다음 카드를 선택하세요.":"다음 카드가 더 높을지 낮을지 선택하세요.";messageEl.className="message";locked=false;setButtons(true)},900)}else restartButton.hidden=false}
function reset(){streak=0;round=1;locked=false;currentCard={rank:1,suit:suits[Math.floor(Math.random()*suits.length)],joker:false};streakEl.textContent="0";bestEl.textContent=best;track.textContent="";const first=makeItem(currentCard,"1번째 카드");first.classList.add("current");first.querySelector("span").textContent="현재 카드";deckItem=makeDeck();track.append(first,deckItem);messageEl.textContent="새 게임은 A부터 시작합니다. 하이 또는 로우를 선택하세요.";messageEl.className="message";restartButton.hidden=true;setButtons(true)}
lowButton.addEventListener("click",()=>choose("low"));highButton.addEventListener("click",()=>choose("high"));restartButton.addEventListener("click",reset);addEventListener("keydown",event=>{if(event.key==="ArrowDown")choose("low");if(event.key==="ArrowUp")choose("high")});reset();
})();

