(()=>{'use strict';
const canvas=document.querySelector('#raceCanvas'),ctx=canvas.getContext('2d'),picker=document.querySelector('#ballPicker'),ranking=document.querySelector('#ranking'),startButton=document.querySelector('#startButton'),resetButton=document.querySelector('#resetButton'),selectedCount=document.querySelector('#selectedCount'),raceState=document.querySelector('#raceState'),errorBox=document.querySelector('#error'),countdown=document.querySelector('#countdown');
const W=620,H=900,R=14,finishY=842;
const palette=[{id:'red',name:'빨강',color:'#ef4035'},{id:'orange',name:'주황',color:'#ff8a27'},{id:'yellow',name:'노랑',color:'#f5cf33'},{id:'green',name:'초록',color:'#38a55a'},{id:'blue',name:'파랑',color:'#3184e6'},{id:'indigo',name:'남색',color:'#3f51a3'},{id:'violet',name:'보라',color:'#9b4bc5'}];
const pins=[];for(let row=0;row<9;row++){const y=180+row*68,offset=row%2?62:28;for(let x=offset;x<W-24;x+=70)pins.push({x,y,r:7+(row%3===0?2:0)})}
const bumpers=[{x:120,y:420,r:29},{x:310,y:378,r:35},{x:500,y:428,r:29},{x:210,y:620,r:26},{x:410,y:620,r:26}];
const rotors=[{cx:145,cy:300,length:132,startAngle:.22,speed:1.25},{cx:475,cy:300,length:132,startAngle:-.22,speed:-1.25},{cx:310,cy:520,length:154,startAngle:0,speed:1.12},{cx:150,cy:710,length:128,startAngle:.35,speed:-1.35},{cx:470,cy:710,length:128,startAngle:-.35,speed:1.35}];rotors.forEach(rotor=>rotor.angle=rotor.startAngle);
let selected=new Set(palette.map(ball=>ball.id)),balls=[],results=[],running=false,raf=0,lastTime=0,startAt=0;
function renderPicker(){picker.textContent='';palette.forEach(ball=>{const button=document.createElement('button');button.type='button';button.className=`ball-option${selected.has(ball.id)?' selected':''}`;button.style.setProperty('--ball',ball.color);button.disabled=running;button.setAttribute('aria-pressed',String(selected.has(ball.id)));button.innerHTML=`<i></i><span>${ball.name}</span>`;button.addEventListener('click',()=>{selected.has(ball.id)?selected.delete(ball.id):selected.add(ball.id);renderPicker();drawIdle()});picker.append(button)});selectedCount.textContent=`${selected.size}개`;startButton.disabled=selected.size<2||running}
function drawBoard(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#172737');g.addColorStop(1,'#0c1822');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='#cfbea0';ctx.lineWidth=5;ctx.strokeRect(12,12,W-24,H-24);ctx.strokeStyle='rgba(255,255,255,.08)';ctx.lineWidth=1;for(let y=70;y<H;y+=70){ctx.beginPath();ctx.moveTo(18,y);ctx.lineTo(W-18,y);ctx.stroke()}ctx.fillStyle='#e9d9bc';ctx.font='900 15px sans-serif';ctx.textAlign='center';ctx.fillText('START',W/2,45);ctx.fillStyle='rgba(239,76,59,.14)';ctx.fillRect(18,finishY,W-36,40);for(let x=18;x<W-18;x+=30){ctx.fillStyle=((x/30)%2)?'#fff7df':'#e94c3b';ctx.fillRect(x,finishY,30,10)}ctx.fillStyle='#fff7df';ctx.fillText('FINISH',W/2,880);
pins.forEach(pin=>{ctx.beginPath();ctx.arc(pin.x,pin.y,pin.r,0,Math.PI*2);ctx.fillStyle='#e7d5b4';ctx.fill();ctx.strokeStyle='#715f48';ctx.lineWidth=2;ctx.stroke()});bumpers.forEach((b,i)=>{ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fillStyle=i%2?'#f3c946':'#e94c3b';ctx.fill();ctx.strokeStyle='#fff4d8';ctx.lineWidth=6;ctx.stroke();ctx.beginPath();ctx.arc(b.x,b.y,b.r-11,0,Math.PI*2);ctx.strokeStyle='rgba(39,33,26,.5)';ctx.lineWidth=3;ctx.stroke()});rotors.forEach(rotor=>{const rail=rotorSegment(rotor);ctx.beginPath();ctx.moveTo(rail.x1,rail.y1);ctx.lineTo(rail.x2,rail.y2);ctx.strokeStyle='#57c7d5';ctx.lineWidth=12;ctx.lineCap='round';ctx.stroke();ctx.strokeStyle='#d8ffff';ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.arc(rotor.cx,rotor.cy,9,0,Math.PI*2);ctx.fillStyle='#fff6dc';ctx.fill();ctx.strokeStyle='#25848f';ctx.lineWidth=3;ctx.stroke()})}
function drawBall(ball){ctx.save();ctx.shadowColor='rgba(0,0,0,.45)';ctx.shadowBlur=8;ctx.shadowOffsetY=5;ctx.beginPath();ctx.arc(ball.x,ball.y,R,0,Math.PI*2);const g=ctx.createRadialGradient(ball.x-5,ball.y-6,2,ball.x,ball.y,R);g.addColorStop(0,'#fff');g.addColorStop(.2,ball.color);g.addColorStop(1,'#2b261f');ctx.fillStyle=g;ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='#fff5df';ctx.lineWidth=2;ctx.stroke();ctx.restore()}
function drawIdle(){drawBoard();const chosen=palette.filter(ball=>selected.has(ball.id));const gap=Math.min(62,(W-80)/Math.max(1,chosen.length-1));const start=W/2-gap*(chosen.length-1)/2;chosen.forEach((ball,index)=>drawBall({x:start+index*gap,y:82,color:ball.color}));if(!chosen.length){ctx.fillStyle='rgba(255,255,255,.55)';ctx.font='700 18px sans-serif';ctx.fillText('오른쪽에서 공을 선택하세요',W/2,90)}}
function collideCircle(ball,target,bounce=1.04){const dx=ball.x-target.x,dy=ball.y-target.y,min=R+target.r,dist=Math.hypot(dx,dy);if(!dist||dist>=min)return;const nx=dx/dist,ny=dy/dist,overlap=min-dist;ball.x+=nx*overlap;ball.y+=ny*overlap;const speed=ball.vx*nx+ball.vy*ny;if(speed<0){ball.vx-=(1+bounce)*speed*nx;ball.vy-=(1+bounce)*speed*ny}ball.vx+=(Math.random()-.5)*22}
function collideRail(ball,rail){const ax=rail.x1,ay=rail.y1,bx=rail.x2,by=rail.y2,abx=bx-ax,aby=by-ay,t=Math.max(0,Math.min(1,((ball.x-ax)*abx+(ball.y-ay)*aby)/(abx*abx+aby*aby))),target={x:ax+abx*t,y:ay+aby*t,r:6};collideCircle(ball,target,.92)}
function rotorSegment(rotor){const dx=Math.cos(rotor.angle)*rotor.length/2,dy=Math.sin(rotor.angle)*rotor.length/2;return{x1:rotor.cx-dx,y1:rotor.cy-dy,x2:rotor.cx+dx,y2:rotor.cy+dy}}
function collideRotor(ball,rotor){const rail=rotorSegment(rotor),ax=rail.x1,ay=rail.y1,abx=rail.x2-ax,aby=rail.y2-ay,t=Math.max(0,Math.min(1,((ball.x-ax)*abx+(ball.y-ay)*aby)/(abx*abx+aby*aby))),px=ax+abx*t,py=ay+aby*t,before=Math.hypot(ball.x-px,ball.y-py);collideRail(ball,rail);if(before<R+7){const rx=px-rotor.cx,ry=py-rotor.cy;ball.vx+=-rotor.speed*ry*.7;ball.vy+=rotor.speed*rx*.7}}
function collideBalls(){for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){const a=balls[i],b=balls[j];if(a.finished||b.finished)continue;const dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy),min=R*2;if(!dist||dist>=min)continue;const nx=dx/dist,ny=dy/dist,overlap=(min-dist)/2;a.x-=nx*overlap;a.y-=ny*overlap;b.x+=nx*overlap;b.y+=ny*overlap;const rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel<0){const impulse=-rel*.88;a.vx-=impulse*nx;a.vy-=impulse*ny;b.vx+=impulse*nx;b.vy+=impulse*ny}}}
function update(dt,now){const elapsed=(now-startAt)/1000,gravity=460+Math.max(0,elapsed-12)*24;rotors.forEach(rotor=>rotor.angle+=rotor.speed*dt);balls.forEach(ball=>{if(ball.finished||now<ball.releaseAt)return;ball.vy+=gravity*dt;ball.vx*=.998;ball.vy*=.999;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x<R+18){ball.x=R+18;ball.vx=Math.abs(ball.vx)*.83+8}if(ball.x>W-R-18){ball.x=W-R-18;ball.vx=-Math.abs(ball.vx)*.83-8}pins.forEach(pin=>collideCircle(ball,pin,.86));bumpers.forEach(b=>collideCircle(ball,b,1.18));rotors.forEach(rotor=>collideRotor(ball,rotor));if(elapsed>18&&ball.vy<95)ball.vy+=80;if(ball.y>finishY+R){ball.finished=true;ball.finishTime=elapsed;results.push(ball);renderRanking();if(results.length===balls.length)finishRace()}});collideBalls()}
function renderRanking(){ranking.textContent='';if(!results.length){const item=document.createElement('li');item.className='empty';item.textContent='아직 도착한 공이 없습니다.';ranking.append(item);return}results.forEach((ball,index)=>{const item=document.createElement('li');item.style.setProperty('--ball',ball.color);item.innerHTML=`<span class="place">${index+1}</span><i class="dot"></i><strong></strong><time>${ball.finishTime.toFixed(2)}초</time>`;item.querySelector('strong').textContent=ball.name;ranking.append(item)})}
function frame(now){if(!running)return;const dt=Math.min(.022,(now-lastTime)/1000||.016);lastTime=now;update(dt,now);drawBoard();balls.forEach(drawBall);raf=requestAnimationFrame(frame)}
function prepareBalls(){const chosen=palette.filter(ball=>selected.has(ball.id));const gap=Math.min(62,(W-100)/Math.max(1,chosen.length-1));const left=W/2-gap*(chosen.length-1)/2;balls=chosen.map((ball,index)=>({ ...ball,x:left+index*gap,y:80-R,vx:(Math.random()-.5)*26,vy:0,releaseAt:performance.now()+index*150,finished:false,finishTime:0}))}
function beginRace(){if(selected.size<2){errorBox.textContent='공을 2개 이상 선택해 주세요.';return}cancelAnimationFrame(raf);errorBox.textContent='';results=[];renderRanking();running=true;renderPicker();resetButton.disabled=true;prepareBalls();let count=3;countdown.hidden=false;countdown.textContent=count;raceState.textContent='출발 준비';const timer=setInterval(()=>{count-=1;if(count>0){countdown.textContent=count;return}clearInterval(timer);countdown.textContent='GO!';raceState.textContent='경기 진행 중';setTimeout(()=>countdown.hidden=true,450);startAt=performance.now()+300;balls.forEach((ball,index)=>ball.releaseAt=startAt+index*150);lastTime=performance.now();raf=requestAnimationFrame(frame)},650)}
function finishRace(){running=false;cancelAnimationFrame(raf);raceState.textContent=`우승 · ${results[0].name}`;startButton.querySelector('span').textContent='같은 공으로 다시';startButton.disabled=false;resetButton.disabled=false;renderPicker()}
function resetSelection(){if(running)return;selected=new Set(palette.map(ball=>ball.id));balls=[];results=[];rotors.forEach(rotor=>rotor.angle=rotor.startAngle);ranking.innerHTML='<li class="empty">경기를 시작하면 순위가 표시됩니다.</li>';raceState.textContent='공을 선택해 주세요';startButton.querySelector('span').textContent='경기 시작';errorBox.textContent='';renderPicker();drawIdle()}
startButton.addEventListener('click',beginRace);resetButton.addEventListener('click',resetSelection);renderPicker();drawIdle();
})();

